### ISSUE TITLE
Божечки мой

### ISSUE THREAD

**Issue by jedi2light** [covrom/gonec#13]
Если ( Мир.Использовать("1С") ) Тогда
НачалоЕсли
        Планета.Остановить();
КонецЕсли

**Comment by slayer** [comment]
Я.Выходить()

**Comment by vosi** [comment]
Ржу("нимагу");

**Comment by covrom** [comment]
такое тоже не прожует :)

**Comment by jedi2light** [comment]
[](https://media1.tenor.com/images/ff7ee6b6f8ea4040afb3f916cf40811d/tenor.gif?itemid=11045679)

**Comment by dmpas** [comment]
> 
> 
> Я.Выходить()

В современном 1С будет что-то вроде этого:
```bsl
&НаПоверхности
Процедура ВыйтиМеня()
  Параметры = Новый Структура("Кто, Откуда", "Я", "Планета");
  ПослеВыхода = Новый ОписаниеОповещения("КогдаУжеВышелИлиНет", Параметры);
  НачатьВыходКоготоОткудато(ПослеВыхода, Параметры);
КонецПроцедуры

&НаПоверхности
Процедура КогдаУжеВышелИлиНет(Результат, ДополнительныеПараметры)
  Если Не Результат Тогда
    ВызватьИсключение СтрШаблон(НСтр("ru='Что-то пошло не так и %1 не вышел с %2';"), ДополнительныеПараметры.Кто, ДополнительныеПараметры.Откуда);
  КонецЕсли;

  ЗавершитьРаботуПланеты();

КонецПроцедуры
```

**Comment by slayer** [comment]
> В современном 1С будет что-то вроде этого:
Вы похоже разбираетесь в этом. Примите мои соболезнования.

**Comment by covrom** [comment]
Такой асинхрон - это боль 1С, умудрились сделать даже хуже, чем в javascript.

**Comment by jedi2light** [comment]
O_O
Тут с js уже сравнивать начали.
Тут нужен герой, который отыщет гифку с аксиомой Эскобара!

**Comment by covrom** [comment]
это настоящие true-программисты, не ругайся на них, все закономерно :)

**Comment by jedi2light** [comment]
Well, it's a pretty unconsciously created task by foolish past me, ha-ha. For everyone who encountered this foolish pseudo-issue, have fun about foolish past me who was surrounded by toxic and self-boundered community producing enough motivation for such fools as me to make that foolish issue which have no sense but to bother developers :) Well, I'm glad that now I'm a bit smarter, ha-ha. ^)
