### ISSUE TITLE
Боль и страдания

### ISSUE THREAD

**Issue by slayer** [covrom/gonec#16]
@covrom Вы извините, но все что я тут вижу, мне доставляет боль. И насколько вижу не только мне.
У меня возникает закономерный вопрос: Зачем Вы это делаете? 
Вы действительно серьезно или это такой неуловимый троллинг? [Poe's law](https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%BA%D0%BE%D0%BD_%D0%9F%D0%BE) ?

Mood:
![image](https://user-images.githubusercontent.com/57521/48254539-fe317b00-e412-11e8-9717-af03ae8a019b.png)

**Comment by antonfrolovsky** [comment]
![Image of pain](https://cs4.pikabu.ru/images/previews_comm/2015-02_3/14239235086312.jpg)

**Comment by covrom** [comment]
Не троллинг. Наработки этого проекта используются в реальных бизнес-приложениях для бизнес-заказчиков. Рядовым программистам это сложно понять :)

**Comment by slayer** [comment]
![image](https://user-images.githubusercontent.com/57521/48336430-ed7a4280-e668-11e8-8005-7e3700640c63.png)
