### ISSUE TITLE
Добавить чат в гиттере.

### ISSUE THREAD

**Issue by Pr-Mex** [covrom/gonec#2]
Предлагаю добавить чат в гиттере, если его ещё нет. 
По аналогии с https://gitter.im/silverbulleters/vanessa-behavior
Если уже есть - повесить бейдж на главной странице репо.

**Comment by covrom** [comment]
Сделано: https://gitter.im/gonec

**Comment by Pr-Mex** [comment]
Ещё я писал про то, чтобы добавить бейдж вот сюда.
![image](https://user-images.githubusercontent.com/8627416/29446401-b16e9b24-83f4-11e7-9e2b-3a9503a910da.png)
