### ISSUE TITLE
План версии 4.0a

### ISSUE THREAD

**Issue by covrom** [covrom/gonec#4]
План для версии 4.0a:
* Будет реализован первый кандидат на параллелизм (помимо уже существующих горутин) - цикл с ключевым словом "Параллельно N", разбивающий выполнение цикла на N параллельно выполняющихся воркеров-горутин, исполняющих тело цикла с отдельными пулами объектов или диапазонами итераторов (каждый в своем окружении). Это позволит обрабатывать большие массивы данных единым понятным алгоритмом, но с использованием параллелизма!
* Работа с таблицами in-memory, в качестве основы будет взято решение https://github.com/ekzhu/datatable
* BoltDB
* API для работы каналов через сеть - горутины Гонца будут общаться между собой и фронтендом посредством каналов по сетевому API. Между собой - бинарный протокол, с фронтендом и 1С - JSON API. Это позволит создавать масштабируемые горизонтально (на множество серверов) решения.

**Comment by nikolaymatrosov** [comment]
Чтобы было что положить на разработку.
