### ISSUE TITLE
Как делать вставки на чистом go?

### ISSUE THREAD

**Issue by JohnyDeath** [covrom/gonec#6]
Пока нет многих объектов, которые нужно использовать, хотелось бы иметь возможность делать вставки на чистом Го.
Как это правильно сделать? Возможно ли?

**Comment by covrom** [comment]
Посмотрите например, на код любого файла в папке (пакете) core.
Хороший пример есть в core.go и в coreserver.go
Обратите внимание, вставки на Го делаются в режиме компиляции интерпретатора после изменения исходных кодов, т.е. не на лету!
